/*
 * This file is part of McIDAS-V
 *
 * Copyright 2007-2016
 * Space Science and Engineering Center (SSEC)
 * University of Wisconsin - Madison
 * 1225 W. Dayton Street, Madison, WI 53706, USA
 * http://www.ssec.wisc.edu/mcidas
 * 
 * All Rights Reserved
 * 
 * McIDAS-V is built on Unidata's IDV and SSEC's VisAD libraries, and
 * some McIDAS-V source code is based on IDV and VisAD source code.  
 * 
 * McIDAS-V is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * McIDAS-V is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser Public License
 * along with this program.  If not, see http://www.gnu.org/licenses.
 */
package edu.wisc.ssec.mcidasv.util;

import java.io.IOException;
import java.net.UnknownHostException;

import edu.wisc.ssec.mcidas.AreaDirectoryList;
import edu.wisc.ssec.mcidas.AreaFileException;
import edu.wisc.ssec.mcidas.adde.AddeException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import visad.VisADException;
import visad.data.mcidas.AreaAdapter;

/**
 * {@code ErrorCodeAreaUtils} sole purpose is to allow McIDAS-V to associate
 * the error codes in
 * {@link edu.wisc.ssec.mcidas.adde.AddeException AddeException} with any
 * exceptions generated by {@link visad.data.mcidas.AreaAdapter AreaAdapter} or
 * {@link edu.wisc.ssec.mcidas.AreaDirectoryList AreaDirectoryList}.
 */
public class ErrorCodeAreaUtils {

    private static final Logger logger = LoggerFactory.getLogger(ErrorCodeAreaUtils.class);

    public static final String GENERIC_EXCEPTION_MESSAGE = "Could not create VisAD data object.";

    /**
     * Disallow instances of {@code ErrorCodeAdapter}.
     */
    private ErrorCodeAreaUtils() { }

    /**
     * Create an {@code AreaAdapter} using the given {@code url}.
     *
     * @param url {@code URL} used to locate AREA. Cannot be {@code null}.
     *
     * @return Either the {@code AreaAdapter} for the given {@code url},
     * or {@code null}.
     *
     * @throws AddeException if the {@code AreaAdapter} had problems.
     */
    public static AreaAdapter createAreaAdapter(final String url) throws AddeException {
        AreaAdapter aa = null;
        try {
            aa = new AreaAdapter(url, false);
        } catch (IOException e) {
            int errorCode = searchStackTrace(e.getCause());
            if (errorCode == 0) {
                throw new AddeException("Could not connect to URL: " + url, e);
            } else {
                throw new AddeException(errorCode, GENERIC_EXCEPTION_MESSAGE, e);
            }
        } catch (VisADException e) {
            int errorCode = searchStackTrace(e.getCause());
            if (errorCode == 0) {
                throw new AddeException(GENERIC_EXCEPTION_MESSAGE, e);
            } else {
                throw new AddeException(errorCode, GENERIC_EXCEPTION_MESSAGE, e);
            }
        }
        return aa;
    }

    /**
     * Create an {@code AreaDirectoryList} using the given {@code url}.
     *
     * @param url {@code URL} used to create AREA directory list. Cannot be {@code null}.
     *
     * @return Either the {@code AreaDirectoryList} for the given {@code url},
     * or {@code null}.
     *
     * @throws AddeException if the {@code AreaDirectoryList} had problems.
     */
    public static AreaDirectoryList createAreaDirectoryList(final String url) throws AddeException {
        AreaDirectoryList adl = null;
        try {
            adl = new AreaDirectoryList(url);
        } catch (AreaFileException e) {
//            logger.trace("exception='{}'", e);
            int errorCode = searchStackTrace(e.getCause());
            throw new AddeException(errorCode, GENERIC_EXCEPTION_MESSAGE, e);
        }
        return adl;
    }

    // yes. this approach is awful. but since i can't modify the visad code
    // (which is what should be done!)...
    private static int searchStackTrace(final Throwable cause) {
        if ((cause == null) || (cause.getMessage() == null)) {
            return -1;
        }

        String message = cause.getMessage().trim();
        if ("DAY= must be used with archived datasets".equals(message)) {
            return -1000;
        } else if ("No images satisfy the selection criteria".equals(message)) {
            return -5000;
        } else if ("Accounting data was not valid".equals(message) || message.startsWith("Invalid project number:")) {
            return -6000;
        } else if ("Band keyword required for multi-banded image".equals(message) || "No BAND(s) specified".equals(message) || "Band required for multi-banded image".equals(message)) {
            return -11011;
        } else if (message.startsWith("Units requested are not available for this")) {
            return -11007;
        } else if ("The requested portion of the image does not exist".equals(message) || "The portion of the image requested does not exist".equals(message) || "Invalid Line SIZE specified".equals(message) || "Invalid Element SIZE specified".equals(message)) {
            return -11010;
        } else if ("Unable to initialize navigation for this image".equals(message)) {
            return -11001;
        } else if (message.endsWith("not present") || "Invalid BAND specified".equalsIgnoreCase(message) || "Invalid band number specified".equalsIgnoreCase(message) || "invalid band requested".equalsIgnoreCase(message)) {
            return -11003;
        } else if (message.startsWith("Band is not available in ") && message.endsWith(" units")) {
            return -7000;
        } else if (message.contains("requested Earth location is not contained in the image") || "Specified Lat/Lon not in image".equals(message)) {
            return -11002;
        } else if (message.startsWith("Image data server unable to resolve this dataset") || message.startsWith("Image directory server unable to resolve this dataset:")) {
            return -118;
        } else if (cause instanceof UnknownHostException) {
            return -114;
        } else {
            Throwable nextCause = cause.getCause();
            if (nextCause != null) {
                return searchStackTrace(nextCause);
            } else {
                return 0;
            }
        }
    }
}
