/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FrmsubsImpl */

#ifndef _Included_FrmsubsImpl
#define _Included_FrmsubsImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FrmsubsImpl
 * Method:    getshm
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getshm
  (JNIEnv *, jclass, jint);

/*
 * Class:     FrmsubsImpl
 * Method:    getnumfrm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getnumfrm
  (JNIEnv *, jclass);

/*
 * Class:     FrmsubsImpl
 * Method:    getcurfrm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getcurfrm
  (JNIEnv *, jclass);

/*
 * Class:     FrmsubsImpl
 * Method:    getfrmsize
 * Signature: ([I[I[I)I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getfrmsize
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     FrmsubsImpl
 * Method:    getfrm
 * Signature: (III[C[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getfrm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jintArray, jintArray, jintArray);

/*
 * Class:     FrmsubsImpl
 * Method:    getdirty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getdirty
  (JNIEnv *, jclass, jint);

/*
 * Class:     FrmsubsImpl
 * Method:    getgrasize
 * Signature: (I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getgrasize
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     FrmsubsImpl
 * Method:    getgra
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_getgra
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     FrmsubsImpl
 * Method:    detshm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_FrmsubsImpl_detshm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
