package edu.wisc.ssec.mcidasv.servermanager;

/**
 * Mostly generated by NetBeans, and then hacked up a bit.
 */
public class AddRemoteAddeEntry extends javax.swing.JPanel {

    /** Creates new form AddRemoteEntry */
    public AddRemoteAddeEntry() {
        initComponents();
    }

    /** 
     * This method is called from within the constructor to initialize the 
     * form.
     */
    private void initComponents() {

        serverLabel.setText("Server:");

        serverField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverFieldActionPerformed(evt);
            }
        });

        groupLabel.setText("Dataset(s):");

        groupField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupFieldActionPerformed(evt);
            }
        });

        acctBox.setText("Specify accounting information:");
        acctBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctBoxActionPerformed(evt);
            }
        });

        userLabel.setText("Username:");

        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });

        projLabel.setText("Project #:");

        capBox.setText("Automatically capitalize datasets and username?");
        capBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout entryPanelLayout = new org.jdesktop.layout.GroupLayout(entryPanel);
        entryPanel.setLayout(entryPanelLayout);
        entryPanelLayout.setHorizontalGroup(
            entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(entryPanelLayout.createSequentialGroup()
                .add(entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(projLabel)
                    .add(userLabel)
                    .add(serverLabel)
                    .add(groupLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(capBox)
                    .add(acctBox)
                    .add(serverField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .add(groupField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .add(userField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .add(projField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addContainerGap())
        );
        entryPanelLayout.setVerticalGroup(
            entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(entryPanelLayout.createSequentialGroup()
                .add(entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(serverField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(serverLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(groupLabel)
                    .add(groupField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(acctBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(userField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(userLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(entryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(projField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(projLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(capBox))
        );

        typePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Types"));

        imageBox.setText("Image");
        imageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageBoxActionPerformed(evt);
            }
        });
        typePanel.add(imageBox);

        pointBox.setText("Point");
        typePanel.add(pointBox);

        gridBox.setText("Grid");
        typePanel.add(gridBox);

        textBox.setText("Text");
        typePanel.add(textBox);

        navBox.setText("Navigation");
        typePanel.add(navBox);

        radarBox.setText("Radar");
        typePanel.add(radarBox);

        verifyAndAddButton.setText("Verify and Add Server");
        verifyAndAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyAndAddButtonActionPerformed(evt);
            }
        });
        actionPanel.add(verifyAndAddButton);

        verifyButton.setText("Verify Server");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });
        actionPanel.add(verifyButton);

        addButton.setText("Add Server");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        actionPanel.add(addButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelButton);

        statusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        statusLabel.setBackground(new java.awt.Color(255, 255, 153));
        statusLabel.setText("Please provide the address of an ADDE server.");

        org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelLayout.createSequentialGroup()
                .add(statusLabel)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(entryPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(typePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(statusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(actionPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(entryPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(typePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(statusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(actionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }

    private void serverFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void groupFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void acctBoxActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void capBoxActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void imageBoxActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void verifyAndAddButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    // the widgets that've been placed in the form.
    private final javax.swing.JCheckBox acctBox = new javax.swing.JCheckBox();
    private final javax.swing.JPanel actionPanel = new javax.swing.JPanel();
    private final javax.swing.JButton addButton = new javax.swing.JButton();
    private final javax.swing.JButton cancelButton = new javax.swing.JButton();
    private final javax.swing.JCheckBox capBox = new javax.swing.JCheckBox();
    private final javax.swing.JPanel entryPanel = new javax.swing.JPanel();
    private final javax.swing.JCheckBox gridBox = new javax.swing.JCheckBox();
    private final javax.swing.JTextField groupField = new javax.swing.JTextField();
    private final javax.swing.JLabel groupLabel = new javax.swing.JLabel();
    private final javax.swing.JCheckBox imageBox = new javax.swing.JCheckBox();
    private final javax.swing.JCheckBox navBox = new javax.swing.JCheckBox();
    private final javax.swing.JCheckBox pointBox = new javax.swing.JCheckBox();
    private final javax.swing.JTextField projField = new javax.swing.JTextField();
    private final javax.swing.JLabel projLabel = new javax.swing.JLabel();
    private final javax.swing.JCheckBox radarBox = new javax.swing.JCheckBox();
    private final javax.swing.JTextField serverField = new javax.swing.JTextField();
    private final javax.swing.JLabel serverLabel = new javax.swing.JLabel();
    private final javax.swing.JLabel statusLabel = new javax.swing.JLabel();
    private final javax.swing.JPanel statusPanel = new javax.swing.JPanel();
    private final javax.swing.JCheckBox textBox = new javax.swing.JCheckBox();
    private final javax.swing.JPanel typePanel = new javax.swing.JPanel();
    private final javax.swing.JTextField userField = new javax.swing.JTextField();
    private final javax.swing.JLabel userLabel = new javax.swing.JLabel();
    private final javax.swing.JButton verifyAndAddButton = new javax.swing.JButton();
    private final javax.swing.JButton verifyButton = new javax.swing.JButton();
}
