package edu.wisc.ssec.mcidasv.servermanager;

import javax.swing.JDialog;
import javax.swing.JFrame;

import edu.wisc.ssec.mcidasv.McIDASV;

// this is accessible via the tools menu or some such thing and allows complete
// control over the available entries.
public class RemoteAddeManager extends javax.swing.JPanel {

   private final McIDASV mcv;
   private final EntryStore entryStore;

    /** Creates new form RemoteAddeManager */
    public RemoteAddeManager(final McIDASV mcv, final EntryStore entryStore) {
        this.mcv = mcv;
        this.entryStore = entryStore;
        initComponents();
    }

    public void showManager() {
        
    }

    public void showAddEntryDialog() {
        JDialog dialog = new JDialog((JFrame)null, "Add New ADDE Server", true);
        AddRemoteAddeEntry entryPanel = new AddRemoteAddeEntry();
        dialog.setContentPane(entryPanel);
        dialog.pack();
        dialog.setResizable(false);
        dialog.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        entryTablePane = new javax.swing.JScrollPane();
        entryTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        newServerButton = new javax.swing.JButton();
        editServerButton = new javax.swing.JButton();
        removeServerButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        entryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Server", "Group", "Username", "Project #", "Type", "Source", "Validity"
            }
        ));
        entryTablePane.setViewportView(entryTable);

        newServerButton.setText("Add New Server");
        buttonPanel.add(newServerButton);

        editServerButton.setText("Edit Server");
        buttonPanel.add(editServerButton);

        removeServerButton.setText("Remove Servers");
        buttonPanel.add(removeServerButton);

        importButton.setText("Import MCTABLE");
        buttonPanel.add(importButton);

        cancelButton.setText("Cancel");
        buttonPanel.add(cancelButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, entryTablePane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 691, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(entryTablePane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editServerButton;
    private javax.swing.JTable entryTable;
    private javax.swing.JScrollPane entryTablePane;
    private javax.swing.JButton importButton;
    private javax.swing.JButton newServerButton;
    private javax.swing.JButton removeServerButton;
    // End of variables declaration

}
