#!/bin/sh

# Change to the directory that the script resides in before executing
dirname=`dirname "$0"`
cd "$dirname"

# Java options
HEAP_SIZE=512m
INIT_HEAP=
THREAD_STACK=
YOUNG_GEN=
JOGL_TOGL=0

# McV/IDV Options
COLLAB_MODE=
COLLAB_PORT=
ENABLE_DEBUG=

# gather up previously set values.
JAVA_FLAGS=-Xmx${HEAP_SIZE} ${INIT_HEAP} ${THREAD_STACK} ${YOUNG_GEN}
MCV_FLAGS=${COLLAB_MODE} ${COLLAB_PORT} ${ENABLE_DEBUG}

################################################################################
# OS specific settings

# Mac OS X settings
if [ `uname -s` = "Darwin" ]; then
	# Set the menu bar name
	JAVA_FLAGS="${JAVA_FLAGS} -Xdock:name=McIDAS-V -Xdock:icon=mcidasv.icns"
	# Look for the Java3D/JOGL package
	if [ -d "jogl" -a -d "java3d" ]; then
		JAVA3D_LIB=${PWD}/java3d
		JAVA3D_CP=${JAVA3D_LIB}/j3dcore.jar:${JAVA3D_LIB}/j3dutils.jar:${JAVA3D_LIB}/vecmath.jar
		if [ "$JOGL_TOGL" -eq 1 ]; then
			JOGL_LIB=${PWD}/jogl
			JOGL_CP=${JOGL_LIB}:${JOGL_LIB}/jogl.jar:${JOGL_LIB}/gluegen-rt.jar
			export DYLD_LIBRARY_PATH=${JOGL_LIB}
			JAVA_FLAGS="${JAVA_FLAGS} -Xbootclasspath/p:${JOGL_CP}:${JAVA3D_CP}"
		fi
	fi
fi
# Done with Mac OS X settings

# Done with OS specific settings
################################################################################

# Set the command name
command="java ${JAVA_FLAGS} -cp idv.jar -jar mcidasv.jar ${MCV_FLAGS} $*"

# Look for java
if [ -f "./jre/bin/java" ]; then
	# We are in the installer directory
	./jre/bin/${command}
else
	if [ -n "${JAVA_HOME}" ]; then
		# Try using JAVA_HOME
		${JAVA_HOME}/bin/${command}
	else 
		# Try just using java
		${command}
	fi
fi
