#!/bin/bash

# Set to 0 in case we can't figure out how to get system memory
SYS_MEM=0

################################################################################
# OS specific settings

# Mac OS X settings
if [ `uname -s` = "Darwin" ]; then
	SYS_MEM_IN=`system_profiler SPHardwareDataType |\
		grep "Memory:" |awk '{print $2 " " $3}'`
	TEST_GB=`echo "${SYS_MEM_IN}" |grep "GB"`
	if [ -n "${TEST_GB}" ]; then
		SYS_MEM=`echo "${SYS_MEM_IN}" |awk '{print $1 * 1024}'`
	else
		SYS_MEM=`echo "${SYS_MEM_IN}" |awk '{print $1}'`
	fi
fi
# Done with Mac OS X settings

# Linux settings
if [ `uname -s` = "Linux" ]; then
	SYS_MEM=`free -m 2>/dev/null |grep "Mem:" |awk '{print $2}'`
fi
# Done with Linux settings

# Solaris settings
if [ `uname -s` = "SunOS" ]; then
	PATH=/usr/sbin:$PATH
	export PATH
	SYS_MEM=`prtconf 2>/dev/null |grep "Memory size:" |awk '{print $3}'`
fi
# Done with Solaris settings

# Done with OS specific settings
################################################################################

# Check if we are a 32bit or 64bit JRE and set SYS_MEM accordingly
JRE_64=
if [ -f "./jre/bin/java" ]; then
	JRE_64=`./jre/bin/java -version 2>&1 |grep "64"`
else
	if [ -n "${JAVA_HOME}" ]; then
		# Try using JAVA_HOME
		JRE_64=`"${JAVA_HOME}/bin/java" -version 2>&1 |grep "64"`
	else 
		JRE_64=`java -version 2>&1 |grep "64"`
	fi
fi
if [ -z "${SYS_MEM}" ]; then
	SYS_MEM=0
fi
if [ -z "${JRE_64}" -a ${SYS_MEM} -gt 1536 ]; then
	SYS_MEM=1536
fi

echo "${SYS_MEM}"