#!/bin/sh

# Change to the directory that the script resides in before executing
dirname=`dirname "$0"`
cd "$dirname"

JAVA_FLAGS=

# Get the amount of system memory
if [ -x ./runMcV-Mem ]; then
	SYS_MEM=`runMcV-Mem`
else
	SYS_MEM=0
fi

################################################################################
# OS specific settings

# Mac OS X settings
if [ `uname -s` = "Darwin" ]; then
	# Set the menu bar name
	JAVA_FLAGS="${JAVA_FLAGS} -Xdock:name=McIDAS-V -Xdock:icon=mcidasv.icns"
fi
# Done with Mac OS X settings

# Done with OS specific settings
################################################################################

# Set the command name
command="java ${JAVA_FLAGS} -jar startupmanager.jar -Didv.sysmem=${SYS_MEM} $*"

# Look for java
if [ -f "./jre/bin/java" ]; then
	# We are in the installer directory
	./jre/bin/${command}
else
	if [ -n "${JAVA_HOME}" ]; then
		# Try using JAVA_HOME
		${JAVA_HOME}/bin/${command}
	else 
		# Try just using java
		${command}
	fi
fi
